###
GET https://gesabsences-32iz.onrender.com/api/v1/etudiants/683c2f126ab4788eded3081b

###
GET https://gesabsences-32iz.onrender.com/api/v1/etudiants/6837b178f156fc62d7fc558f

###
GET https://gesabsences-32iz.onrender.com/api/v1/etudiants/matricule/MAT10

###
POST https://gesabsences-32iz.onrender.com/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "login": "admin0@gmail.com",
  "password": "passer"
}

###
GET https://gesabsences-32iz.onrender.com/api/v1/presences/type=ABSENT

###
GET https://gesabsences-32iz.onrender.com/api/v1/presences/68388d5eee3dc7deb1b87155

###
Post https://gesabsences-32iz.onrender.com/api/v1/justificatifs
Accept: application/json
Content-Type: application/json

{
  "motif": "Malade depuis 3 jours",
  "presenceId": "68388d5eee3dc7deb1b87158"
}

###
GET http://localhost:8080/api/v1/presences/type=PRESENT/etudiant/683de8bf252c3135dafe370e

###
GET http://localhost:8080/api/v1/presences/683c2f126ab4788eded3084d

###
GET http://localhost:8080/api/v1/presences/etudiant/MAT10

###
GET https://gesabsences-32iz.onrender.com/api/v1/cours/etudiant/683de8bf252c3135dafe3713?date=2025-06-13

###
GET https://gesabsences-32iz.onrender.com/api/web/v1/etudiants/paginate?page=0&size=10

###
GET http://localhost:8080/api/web/v1/etudiants/classe/683c2f086ab4788eded3079d

###
GET http://localhost:8080/api/web/v1/etudiants/status/true

###
GET https://gesabsences-32iz.onrender.com/api/web/v1/presences/type=PRESENT

###
GET http://localhost:8080/api/web/v1/presences/type=ABSENT/cours/683de8b6252c3135dafe3708

###
GET http://localhost:8080/api/web/v1/presences/type=ABSENT/date=2025-06-06


###
GET https://gesabsences-32iz.onrender.com/api/web/v1/justificatifs/683e574a0061f2f63a4813ca

###
Put https://gesabsences-32iz.onrender.com/api/web/v1/justificatifs/683e4d44e7a0f555d7e72ba1
Accept: application/json
Content-Type: application/json

{
  "validation": true,
  "adminId": "683de8b4252c3135dafe36fd"
}

###
GET http://localhost:8080/api/web/v1/presences/683c2f126ab4788eded3084d

###
GET http://localhost:8080/api/web/v1/classes


###
POST https://gesabsences-32iz.onrender.com/api/v1/justificatifs/create
Accept: application/json
Content-Type: multipart/form-data; boundary=---011000010111000001101001

-----011000010111000001101001
Content-Disposition: form-data; name="motif"

Malade depuis 3 jours
-----011000010111000001101001
Content-Disposition: form-data; name="presenceId"

683e4d3ae7a0f555d7e728b3
-----011000010111000001101001
Content-Disposition: form-data; name="multipartFiles"; filename="just1.jpg"
Content-Type: image/jpeg

< C:/Users/assan/Downloads/just1.jpg
-----011000010111000001101001
Content-Disposition: form-data; name="multipartFiles"; filename="just2.png"
Content-Type: image/png

< C:/Users/assan/Downloads/just2.png
-----011000010111000001101001--

###
GET http://localhost:8080/api/web/v1/etudiants/classe/683de8b4252c3135dafe36fb/status/true

###
GET https://gesabsences-32iz.onrender.com/api/web/v1/cours

###
GET http://localhost:8080/api/web/v1/justificatifs/presence/683e4d3ae7a0f555d7e728b3

###
GET http://localhost:8080/api/web/v1/presences/justify/true

###
GET http://localhost:8080/api/web/v1/presences/type=ABSENT/cours=683de8b6252c3135dafe3708/date=2025-06-11

###
GET http://localhost:8080/api/web/v1/presences/type=ABSENT/cours=683de8b6252c3135dafe3708/etat=true/date=2025-06-11

###
GET https://gesabsences-32iz.onrender.com/api/v1/presences/type=RETARD/etudiant/683de8bf252c3135dafe3739