###
GET https://gesabsences-32iz.onrender.com/api/v1/etudiants/683c2f126ab4788eded3081b

###
GET https://gesabsences-32iz.onrender.com/api/v1/etudiants/6837b178f156fc62d7fc558f

###
GET https://gesabsences-32iz.onrender.com/api/v1/etudiants/matricule/MAT10

###
POST http://localhost:8080/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "login": "etudiant0@gmail.com",
  "password": "passer"
}

###
GET https://gesabsences-32iz.onrender.com/api/v1/presences/type=ABSENT

###
GET https://gesabsences-32iz.onrender.com/api/v1/presences/68388d5eee3dc7deb1b87155

###
Post https://gesabsences-32iz.onrender.com/api/v1/justificatifs
Accept: application/json
Content-Type: application/json

{
  "motif": "Malade depuis 3 jours",
  "presenceId": "68388d5eee3dc7deb1b87158"
}

###
GET http://localhost:8080/api/v1/presences/type=PRESENT/etudiant/683c2f126ab4788eded3081b

###
GET http://localhost:8080/api/v1/presences/683c2f126ab4788eded3084d

###
GET https://gesabsences-32iz.onrender.com/api/v1/presences/etudiant/MAT5

###
GET http://localhost:8080/api/v1/cours/etudiant/683c2f126ab4788eded3081b

###
GET http://localhost:8080/api/web/v1/etudiants?page=0&size=10

###
GET http://localhost:8080/api/web/v1/etudiants/classe/683c2f086ab4788eded3079d

###
GET http://localhost:8080/api/web/v1/etudiants/status/true

###
GET http://localhost:8080/api/web/v1/presences/type=ABSENT

###
GET http://localhost:8080/api/web/v1/presences/type=ABSENT/cours/683c2f096ab4788eded307a3

###
GET http://localhost:8080/api/web/v1/presences/type=PRESENT/date=2025-06-01


###
GET https://gesabsences-32iz.onrender.com/api/web/v1/justificatifs/683b7934dee25772c419cfa7

###
Put https://gesabsences-32iz.onrender.com/api/web/v1/justificatifs/683c2f156ab4788eded308b1
Accept: application/json
Content-Type: application/json

{
  "validation": true
}

###
GET http://localhost:8080/api/web/v1/presences/683c2f126ab4788eded3084d