###
GET https://gesabsences-32iz.onrender.com/api/v1/etudiants/1

###
GET http://localhost:8080/api/v1/etudiants/6837b178f156fc62d7fc558f

###
GET http://localhost:8080/api/v1/etudiants/matricule/MAT10

###
POST http://localhost:8080/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "login": "admin0@gmail.com",
  "password": "passer"
}

###
GET http://localhost:8080/api/v1/presences/type=ABSENT

###
GET http://localhost:8080/api/v1/presences/68388d5eee3dc7deb1b87155

###
Post http://localhost:8080/api/v1/justificatifs
Accept: application/json
Content-Type: application/json

{
  "motif": "Malade depuis 3 jours",
  "presenceId": "68388d5eee3dc7deb1b87158"
}

###
GET http://localhost:8080/api/v1/presences/type=ABSENT/etudiant/68388d5dee3dc7deb1b87124
